# get all tours
GET localhost:3000/api/v1/tours
Accept: application/json

###

# get /top-5-cheap
GET localhost:3000/api/v1/tours/top-5-cheap
Accept: application/json

###

# get /tour-stats
GET localhost:3000/api/v1/tours/tour-stats
Accept: application/json

###

# get /tour-plan
GET localhost:3000/api/v1/tours/monthly-plan/2021
Accept: application/json

###

# get tour by id
GET localhost:3000/api/v1/tours/6378902d9d10686379eb5d8f
Accept: application/json

###

# post new tour
POST localhost:3000/api/v1/tours
content-type: application/json

{
  "name": "This is  a super secret tour 2",
  "duration": 3,
  "maxGroupSize": 12,
  "difficulty": "easy",
  "ratingsAverage": 4.7,
  "ratingsQuantity": 7,
  "price": 1497,
  "summary": "Enjoy the Northern Lights in one of the best places in the world",
  "description": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua, ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum!\nDolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur, exercitation ullamco laboris nisi ut aliquip. Lorem ipsum dolor sit amet, consectetur adipisicing elit!",
  "imageCover": "tour-9-cover.jpg",
  "images": [
    "tour-9-1.jpg",
    "tour-9-2.jpg",
    "tour-9-3.jpg"
  ],
  "startDates": [
    "2021-12-16T10:00:00.000Z",
    "2022-01-16T10:00:00.000Z",
    "2022-12-12T10:00:00.000Z"
  ],
  "secretTour": true
}

###

# patch tour
PATCH localhost:3000/api/v1/tours/634f05ae0ef44a39bb4544b6
Content-type: application/json

{
  "ratingsAverage": 4.9
}

###

# delete tour
DELETE localhost:3000/api/v1/tours/634eb44461dcfea095503498

###
